-- Tabla SERVICIOS (RN-13/14: Validación de agenda)
CREATE TABLE IF NOT EXISTS servicios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_servicio VARCHAR(50) UNIQUE NOT NULL,
    cliente_id INT NOT NULL,
    tecnico_asignado_id INT,
    descripcion TEXT NOT NULL,
    tipo_servicio VARCHAR(100),
    estado ENUM('pendiente', 'programado', 'en_proceso', 'completado', 'cancelado') DEFAULT 'pendiente',
    fecha_solicitud DATE NOT NULL,
    fecha_programada DATE,
    hora_inicio TIME,
    hora_fin TIME,
    ubicacion TEXT,
    valor_estimado DECIMAL(15,2),
    valor_final DECIMAL(15,2),
    observaciones TEXT,
    activo TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT,
    FOREIGN KEY (tecnico_asignado_id) REFERENCES tecnicos(id) ON DELETE RESTRICT,
    INDEX idx_numero_servicio (numero_servicio),
    INDEX idx_cliente_id (cliente_id),
    INDEX idx_tecnico_id (tecnico_asignado_id),
    INDEX idx_estado (estado),
    INDEX idx_fecha_programada (fecha_programada),
    INDEX idx_activo (activo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabla de servicios termográficos';
