-- Tabla CUENTAS_COBRO (RN-06: Generación automática CC-YYYY-XXXX)
CREATE TABLE IF NOT EXISTS cuentas_cobro (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(50) UNIQUE NOT NULL COMMENT 'Formato: CC-YYYY-XXXX',
    cliente_id INT NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    fecha_pago DATE,
    estado ENUM('pendiente', 'parcial', 'pagada', 'vencida', 'cancelada') DEFAULT 'pendiente',
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
    impuesto_iva DECIMAL(15,2) NOT NULL DEFAULT 0,
    descuento DECIMAL(15,2) DEFAULT 0,
    total DECIMAL(15,2) NOT NULL DEFAULT 0,
    moneda VARCHAR(3) DEFAULT 'COP',
    metodo_pago VARCHAR(100),
    referencia_externa VARCHAR(255),
    notas TEXT,
    usuario_creador_id INT,
    activo TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_creador_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    INDEX idx_numero (numero),
    INDEX idx_cliente_id (cliente_id),
    INDEX idx_estado (estado),
    INDEX idx_fecha_vencimiento (fecha_vencimiento),
    INDEX idx_activo (activo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabla de cuentas de cobro - RN-06';
